# Generated by Django 4.0.3 on 2022-03-11 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('approved', models.BooleanField(null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.game')),
                ('game_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.gamesystem')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.kid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.room')),
            ],
        ),
        migrations.CreateModel(
            name='KidMeetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.kid')),
                ('meet_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.meetup')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.kid'),
        ),
        migrations.CreateModel(
            name='FaveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.kid')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.room')),
            ],
        ),
        migrations.CreateModel(
            name='FaveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.game')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiddosapi.kid')),
            ],
        ),
    ]
