# Generated by Django 4.0.3 on 2022-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddosapi', '0002_meetup_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
