# Generated by Django 4.0.3 on 2022-03-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiddosapi', '0003_alter_game_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kid', to=settings.AUTH_USER_MODEL),
        ),
    ]
