# Generated by Django 4.0.3 on 2022-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiddosapi', '0006_game_fave_game_room_fave_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='fave_game',
            new_name='fave_games',
        ),
    ]
